### PR TITLE
Multichain dApp (Rinkeby & Mumbai) + Some UI Refactorings

### PR DESCRIPTION
**Pull request by wottpal**
IMPORTANT: 
1. Make sure to check your frontend `.env.local` again from `.env.local.example` (a few things have changed)
2. Make sure to re-install dependencies with `npm` like described in previous PR (https://github.com/yieldgate/yieldgate/pull/8)

Changes:
* frontend: environment variable `NEXT_PUBLIC_DEFAULT_CHAIN` added (for read-calls w/o wallet/signer connected)
* frontend: environment variable `NEXT_PUBLIC_SUPPORTED_CHAINS` is now actually used in `wagmiClient.ts`
* frontend: added `ChainSwitchMenu`
* frontend: refactored ens-domain fetching into new `useEnsDomain` hook
* frontend: made index + creator-page adaptive to different chains
* frontend: refactored creators-list within index into `CreatorsList` and `CreatorsListItem`
* frontend: made `CreatorsList` filterable and "paginatable"
* frontend: refactored `CreatorCard` into `CreatorCardDetails`, `CreatorCardActions`, and `CreatorCardNumbers`
* frontend: refactored creator-related read-transactions into new `creatorReadHooks`
* frontend: new hook `useYieldgateContract` always returns the current supported chain, and according contract addresses for read/write calls

probably forgot some things 🤷‍♂️

### CODE REVIEW

**Comment by raulrpearson** [comment]
I'll have a look 👍

**Comment by wottpal** [comment]
@raulrpearson the error you noticed should be fixed now. please have a check and merge if that's the case :)

**Review by raulrpearson — APPROVED** [review]
@wottpal, looking good. I'm in favour of merging as is and opening up issues for future work as we find problems with the current implementation and venture to solve the issues we already know about. Some comments:

- I'm not sure why we're not having a problem with this but the workspaces property in `package.json` [expects an array](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#workspaces):

```json
  "workspaces": [
    "./packages/*"
  ]
```

- Do we want to modify the instructions on the readme to suggest `npm run hardhat:chain` and `npm hardhat:deploy` or do we want to add `chain` and `deploy` scripts that point to those longer-name scripts?

- Just for the record, `npm install` results in "54 vulnerabilities (2 low, 13 moderate, 38 high, 1 critical)". All except one come from `ganache-core`, which is included only as a dev dependency on the contracts workspace, if I'm not mistaken. All of them seem to come down to `waffle`. I think we're good, given this and the fact that this PR is headed towards `develop`.

- When I switch wallet address in Metamask I need to navigate or refresh for the avatar to change on the nav bar. The creator card and the new post form do respond to that change immediately, though. I also need to navigate/refresh for the supporters card to refresh. In fact, the supporters card seems totally messed up but IIRC you told me about it and that we plan to solve it with the subgraph story.

Apart from these comments, I did some smoke testing and everything seems to be working fine. Great job, really, I quite like the new UI features and the creator card refactoring.

**Comment by wottpal** [comment]
thanks, @raulrpearson. many good points.

* chore: updated the `README`
* chore: updated the `package.json` workspaces declaration
* frontend: fixed the `BlockiesAvatar` component to update on address change

I'll merge and re-deploy now.

**Pull request merged**
